<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Tallyhouse.Infrastructure\Tallyhouse.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tallyhouse.IntegrationTests" />
  </ItemGroup>

</Project>
