// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tallyhouse.Infrastructure.Catalog;

#nullable disable

namespace Tallyhouse.Infrastructure.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260923140204_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tallyhouse.Infrastructure.Catalog.CatalogRevisionEntity", b =>
                {
                    b.Property<bool>("Singleton")
                        .HasColumnType("boolean")
                        .HasColumnName("singleton");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint")
                        .HasColumnName("revision");

                    b.HasKey("Singleton")
                        .HasName("pk_catalog_revision");

                    b.ToTable("catalog_revision", null, t =>
                        {
                            t.HasCheckConstraint("ck_catalog_revision_singleton", "singleton");
                        });

                    b.HasData(
                        new
                        {
                            Singleton = true,
                            Revision = 0L
                        });
                });

            modelBuilder.Entity("Tallyhouse.Infrastructure.Catalog.EventSchemaEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("EventName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("spec");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ProjectId", "EventName", "Version")
                        .HasName("pk_event_schemas");

                    b.ToTable("event_schemas", null, t =>
                        {
                            t.HasCheckConstraint("ck_event_schemas_version", "version BETWEEN 1 AND 65535");
                        });
                });

            modelBuilder.Entity("Tallyhouse.Infrastructure.Catalog.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<byte[]>("ReadKeyHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("read_key_hash");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("settings");

                    b.Property<byte[]>("WriteKeyHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea")
                        .HasColumnName("write_key_hash");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("ReadKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_read_key_hash");

                    b.HasIndex("WriteKeyHash")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_write_key_hash");

                    b.ToTable("projects", null, t =>
                        {
                            t.HasCheckConstraint("ck_projects_name_length", "length(name) BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("Tallyhouse.Infrastructure.Catalog.EventSchemaEntity", b =>
                {
                    b.HasOne("Tallyhouse.Infrastructure.Catalog.ProjectEntity", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_schemas_projects_project_id");
                });
#pragma warning restore 612, 618
        }
    }
}
